apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grantdeck-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grantdeck
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy
      ports:
        - port: 8000
          protocol: TCP
        - port: 8001
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitor
      ports:
        - port: 8000
          protocol: TCP
    - from:
        - podSelector: {}
      ports:
        - port: 8000
          protocol: TCP
        - port: 8001
          protocol: TCP
