apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: grantdeck-als
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: EnvoyProxy
      namespace: envoy
  to:
    - group: ""
      kind: Service
