apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grantdeck
resources:
  - ../../base
configMapGenerator:
  - name: grantdeck-config
    envs:
      - config.env
secretGenerator:
  - name: grantdeck-secret
    envs:
      - secret.env
replacements:
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.K8S_NAMESPACE
    targets:
      - select:
          version: v1
          kind: ConfigMap
          name: grantdeck-config
        fieldPaths:
          - metadata.namespace
      - select:
          version: v1
          kind: Secret
          name: grantdeck-secret
        fieldPaths:
          - metadata.namespace
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: grantdeck
        fieldPaths:
          - metadata.namespace
      - select:
          version: v1
          kind: Service
          name: grantdeck
        fieldPaths:
          - metadata.namespace
      - select:
          version: v1
          kind: Service
          name: grantdeck-postgres
        fieldPaths:
          - metadata.namespace
      - select:
          group: apps
          version: v1
          kind: StatefulSet
          name: grantdeck-postgres
        fieldPaths:
          - metadata.namespace
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - metadata.namespace
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.ROUTE_HOST
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - spec.hostnames.0
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.ROUTE_PREFIX
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - spec.rules.0.matches.0.path.value
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.GATEWAY_NAME
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - spec.parentRefs.0.name
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.GATEWAY_NAMESPACE
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - spec.parentRefs.0.namespace
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.GATEWAY_SECTION
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          name: grantdeck
        fieldPaths:
          - spec.parentRefs.0.sectionName
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.IMAGE
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: grantdeck
        fieldPaths:
          - spec.template.spec.containers.[name=grantdeck].image
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.ROUTE_HOST
    targets:
      - select:
          group: apps
          version: v1
          kind: Deployment
          name: grantdeck
        fieldPaths:
          - spec.template.spec.containers.[name=grantdeck].startupProbe.httpGet.httpHeaders.0.value
          - spec.template.spec.containers.[name=grantdeck].livenessProbe.httpGet.httpHeaders.0.value
          - spec.template.spec.containers.[name=grantdeck].readinessProbe.httpGet.httpHeaders.0.value
  - source:
      kind: ConfigMap
      name: grantdeck-config
      fieldPath: data.POSTGRES_STORAGE
    targets:
      - select:
          group: apps
          version: v1
          kind: StatefulSet
          name: grantdeck-postgres
        fieldPaths:
          - spec.volumeClaimTemplates.0.spec.resources.requests.storage
