# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('join_code_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('join_requires_approval', models.BooleanField(default=True)),
                ('administrators', models.ManyToManyField(related_name='administered_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active')], default='requested', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.resource')),
            ],
            options={
                'ordering': ['project', 'resource'],
            },
        ),
        migrations.CreateModel(
            name='StaticToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_suffix', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('allowed_count', models.PositiveBigIntegerField(default=0)),
                ('denied_count', models.PositiveBigIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='authz.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Bearer token',
                'verbose_name_plural': 'Bearer tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_count', models.PositiveBigIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='authz.resource')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='authz.statictoken')),
            ],
            options={
                'verbose_name': 'Bearer token resource usage',
                'verbose_name_plural': 'Bearer token resource usage',
                'ordering': ['resource__url'],
                'constraints': [models.UniqueConstraint(fields=('token', 'resource'), name='unique_token_resource_usage')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='authz.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(related_name='projects', through='authz.ProjectResource', to='authz.resource'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
        migrations.AddConstraint(
            model_name='projectresource',
            constraint=models.UniqueConstraint(fields=('project', 'resource'), name='unique_project_resource'),
        ),
    ]
