# Generated by Django 6.0.7

from django.db import migrations, models
import django.core.validators


def backfill_project_shortcuts(apps, schema_editor):
    Project = apps.get_model('authz', 'Project')
    for project in Project.objects.filter(shortcut__isnull=True):
        project.shortcut = f'project-{project.pk}'
        project.save(update_fields=['shortcut'])


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shortcut',
            field=models.CharField(
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[A-Za-z0-9_-]+$',
                        'Use only ASCII letters, digits, underscores, and hyphens.',
                    ),
                ],
            ),
        ),
        migrations.RunPython(backfill_project_shortcuts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='shortcut',
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[A-Za-z0-9_-]+$',
                        'Use only ASCII letters, digits, underscores, and hyphens.',
                    ),
                ],
            ),
        ),
    ]
