# Generated by Django 6.0.7 on 2026-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('user_identifier', models.CharField(max_length=150)),
                ('project_identifier', models.PositiveBigIntegerField()),
                ('project_shortcut', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=200)),
                ('token_count', models.PositiveBigIntegerField(default=0)),
                ('request_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_shortcut', 'user_identifier', 'model_name'],
                'indexes': [models.Index(fields=['day', 'project_identifier', 'model_name'], name='usage_daily_day_f14708_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'user_identifier', 'project_identifier', 'project_shortcut', 'model_name'), name='unique_daily_usage_identity')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=128, unique=True)),
                ('user_identifier', models.CharField(max_length=150)),
                ('project_identifier', models.PositiveBigIntegerField()),
                ('project_shortcut', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=200)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('token_count', models.PositiveBigIntegerField()),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at', 'user_identifier', 'project_shortcut'], name='usage_usage_occurre_de16cd_idx')],
            },
        ),
    ]
